- id: commit_msg_prefix
  name: Add task prefix to commit message
  description: Add current branch name as prefix to COMMITMSG.
  entry: commit_msg_prefix
  language: python
  always_run: true
  stages: [ prepare-commit-msg ]

- id: linked_todos
  name: Check for linked todos
  description: Prevent committing with todos linked to current branch name.
  entry: linked_todos
  stages: [ commit ]
